AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
